version: '2.0'

services:
  web:
    container_name: web
    image: "anhchienhoang/sf4-cqrs-es-demo"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www:cached
    ports:
      - "80:80"
    links:
      - db
      - rabbitmq
    working_dir: /var/www
    stdin_open: true
    tty: true
    environment:
      - APP_ENV=dev
      - APP_SECRET=39465ba56d4a766c6c7a8147f0a97e73
      - DATABASE_URL=mysql://root:root@db:3306/web
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_API_PORT=5672
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/.dump:/docker-entrypoint-initdb.d
      - ./.docker/pfm/mysql/conf.d:/etc/mysql/conf.d
      - ./.docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=web
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    stdin_open: true
    tty: true

  messages_consumer:
    container_name: messages_consumer
    image: "anhchienhoang/sf4-cqrs-es-demo"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www:cached
    links:
      - db
      - rabbitmq
    working_dir: /var/www
    environment:
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
    command: php bin/console messenger:consume-messages

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
    stdin_open: true
    tty: true
